apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"ose-rbac-k8s.app-test.solution.sbt"},"name":"walle-cr"},"rules":[{"apiGroups":[""],"resources":["namespaces","services"],"verbs":["get","list","watch"]},{"apiGroups":["apps"],"resources":["deployments"],"verbs":["get","list","watch"]},{"apiGroups":["apps.openshift.io"],"resources":["deploymentconfigs"],"verbs":["get","list","watch"]},{"apiGroups":["autoscaling"],"resources":["horizontalpodautoscalers"],"verbs":["get","list","watch"]},{"apiGroups":["networking.istio.io"],"resources":["destinationrules","envoyfilters","gateways","serviceentries","sidecars","virtualservices"],"verbs":["get","list","watch"]},{"apiGroups":["template.openshift.io"],"resources":["templates"],"verbs":["get","list","watch"]},{"apiGroups":["maistra.io"],"resources":["servicemeshmemberrolls"],"verbs":["get","list","watch"]},{"apiGroups":["project.openshift.io"],"resources":["projects"],"verbs":["get","list","watch"]}]}
  creationTimestamp: "2024-08-06T12:33:22Z"
  labels:
    argocd.argoproj.io/instance: ose-rbac-k8s.app-test.solution.sbt
  name: walle-cr-test
  resourceVersion: "895"
  uid: ad41e321-4f65-41eb-b9ea-27cef2f287cc
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
    resources:
      - destinationrules
      - envoyfilters
      - gateways
      - serviceentries
      - sidecars
      - virtualservices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - template.openshift.io
    resources:
      - templates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - maistra.io
    resources:
      - servicemeshmemberrolls
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
      - list
      - watch