apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: walle-cr-test
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
  - apiGroups:
      - networking.istio.io
    resources:
      - destinationrules
      - envoyfilters
      - gateways
      - serviceentries
      - sidecars
      - virtualservices
    verbs:
      - get
      - list
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
  - apiGroups:
      - template.openshift.io
    resources:
      - templates
    verbs:
      - get
      - list
  - apiGroups:
      - maistra.io
    resources:
      - servicemeshmemberrolls
    verbs:
      - get
      - list
  - apiGroups:
      - project.openshift.io
    resources:
      - projects
    verbs:
      - get
      - list
