apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: manager-crbc
  name: manager-crbc
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: manager-crbc
  replicas: 1
  template:
    metadata:
      labels:
        app: manager-crbc
    spec:
      containers:
      - name: oauth2-proxy
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: >-
          {{ .Values.imageoauth2proxy.repository }}:{{ .Values.imageoauth2proxy.tag }}
        args:
          - '--provider=openshift'
          - '--https-address=0.0.0.0:4180'
          - '--http-address='
          - >-
            --redirect-url=https://{{ .Values.fqdn.route }}/oauth/callback
          - '--client-id=manager-crbc-oautclient'
          - '--client-secret={{ .Values.oauth2proxy.secret }}'
          - '--cookie-secret=VXNSZ1FqMXFId2YwWWt3UlVTUjFXQT09'
          - '--upstream=http://localhost:8080'
          - '--set-xauthrequest=true'
          - '--pass-basic-auth=true'
          - '--pass-access-token=true'
          - '--pass-user-headers=true'
          - '--pass-user-bearer-token=true'
          - '--pass-host-header=true'
          - '--requestheader-extra-headers-prefix=X-Forwarded-Preferred-Username'
          - '--requestheader-group-headers=X-Remote-Group'
          - '--requestheader-username-headers=X-Forwarded-Preferred-Username'
          - '--tls-cert=/etc/tls/tls.crt'
          - '--tls-key=/etc/tls/tls.key'
          - >-
            --openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        ports:
        - containerPort: 4180
          name: http-oauth2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
          - name: tls-secret
            readOnly: true
            mountPath: /etc/tls
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: files
          mountPath: /files
          readOnly: true
      volumes:
      - name: files
        configMap:
          name: templates
      - name: tls-secret
        secret:
          secretName: manager-crbc-dap-secret
          defaultMode: 420
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        node-role.kubernetes.io/service: ""
      tolerations:
      - effect: NoExecute
        key: node-role.kubernetes.io/service
