apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: manager-crbc-dap-secret
  labels:
    app: manager-crbc
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 4180
      protocol: TCP
      targetPort: 4180
      name: http-oauth2
  selector:
    app: manager-crbc
